# Generated by Django 4.1 on 2024-05-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_shoe_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='store',
        ),
    ]
