# Generated by Django 4.1 on 2024-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_remove_shoe_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='stores',
            field=models.ManyToManyField(to='www.store'),
        ),
    ]
